# Generated by Django 2.2.4 on 2019-09-28 04:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValueArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=timezone.now)),
                ('data_input', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_output', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
